### ISSUE TITLE
Create Data Type

### ISSUE THREAD

**Issue by EarthmanT** [cloudify-incubator/cloudify-key-plugin#1]
- [ ] create a data type ```key```
```
data_types:
  cloudify.datatypes.key:
    properties:
      algorithm:
        default: RSA
      bits:
        default: 2048
      comment:
        type: string
        required: false
      passphrase:
        type: string
        required: false
      OpenSSH_format:
        type: boolean
        required: false
```
